# config/packages/workflow.yaml
framework:
    workflows:
        schede_pai_creating:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\EntityPAI\SchedaPAI
            initial_marking: nuova
            places:
                nuova: ~
                approvata: ~
                attiva: ~
                verifica: ~
                in_attesa_di_chiusura: ~
                in_attesa_di_chiusura_con_rinnovo: ~
                chiusa: ~
                chiusa_con_rinnovo: ~
                chiusura_forzata: ~
            transitions:
                approva:
                    from: nuova
                    to:   approvata
                attiva:
                    from: approvata
                    to:   attiva
                verifica:
                    from: attiva
                    to:   verifica
                attendi_chiusura:
                    from: verifica
                    to:   in_attesa_di_chiusura
                attendi_chiusura_con_rinnovo:
                    from: verifica
                    to:   in_attesa_di_chiusura_con_rinnovo
                chiudi:
                    from: in_attesa_di_chiusura
                    to: chiusa
                chiudi_e_rinnova:
                    from: in_attesa_di_chiusura_con_rinnovo
                    to: chiusa_con_rinnovo
                approva_per_cancellazione:
                    from: attiva
                    to: approvata
                verifica_per_errore1:
                    from: in_attesa_di_chiusura
                    to: verifica
                verifica_per_errore2:
                    from: in_attesa_di_chiusura_con_rinnovo
                    to: verifica
                attiva_per_cambio_dati1:
                    from: in_attesa_di_chiusura
                    to: attiva
                attiva_per_cambio_dati2:
                    from: in_attesa_di_chiusura_con_rinnovo
                    to: attiva
                attiva_per_cambio_dati3:
                    from: verifica
                    to: attiva
                chiusura_forzata1:
                    from: nuova
                    to: chiusura_forzata
                chiusura_forzata2:
                    from: approvata
                    to: chiusura_forzata
                chiusura_forzata3:
                    from: attiva
                    to: chiusura_forzata
                chiusura_forzata4:
                    from: verifica
                    to: chiusura_forzata
                chiusura_forzata5:
                    from: in_attesa_di_chiusura
                    to: chiusura_forzata
                chiusura_forzata6:
                    from: in_attesa_di_chiusura_con_rinnovo
                    to: chiusura_forzata
