version: '3'

services:

  db:
    image: mysql:8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: 'unless-stopped'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: MetaPass123
      MYSQL_USER: mm_symfony
      MYSQL_PASSWORD: mm_pass
      MYSQL_DATABASE: mm_db
    volumes:
      - './docker-data-volumes/mysql/data:/var/lib/mysql'
