<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230202145532 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel DROP FOREIGN KEY FK_90EA910F7A387E36');
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel DROP FOREIGN KEY FK_90EA910F32524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel ADD CONSTRAINT FK_90EA910F7A387E36 FOREIGN KEY (autore_barthel_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel ADD CONSTRAINT FK_90EA910F32524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden DROP FOREIGN KEY FK_150FFD332524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden DROP FOREIGN KEY FK_150FFD348BA978');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden ADD CONSTRAINT FK_150FFD332524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden ADD CONSTRAINT FK_150FFD348BA978 FOREIGN KEY (autore_braden_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni DROP FOREIGN KEY FK_52863577AEB51382');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni DROP FOREIGN KEY FK_5286357732524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni ADD CONSTRAINT FK_52863577AEB51382 FOREIGN KEY (autore_lesioni_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni ADD CONSTRAINT FK_5286357732524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq DROP FOREIGN KEY FK_652E7A3FD0161416');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq DROP FOREIGN KEY FK_652E7A3F32524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq ADD CONSTRAINT FK_652E7A3FD0161416 FOREIGN KEY (autore_spmsq_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq ADD CONSTRAINT FK_652E7A3F32524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti DROP FOREIGN KEY FK_38D7D6432524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti DROP FOREIGN KEY FK_38D7D641FA7127F');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti ADD CONSTRAINT FK_38D7D6432524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti ADD CONSTRAINT FK_38D7D641FA7127F FOREIGN KEY (autore_tinetti_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas DROP FOREIGN KEY FK_D92348348FB292');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas DROP FOREIGN KEY FK_D92348332524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas ADD CONSTRAINT FK_D92348348FB292 FOREIGN KEY (autore_vas_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas ADD CONSTRAINT FK_D92348332524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel DROP FOREIGN KEY FK_90EA910F7A387E36');
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel DROP FOREIGN KEY FK_90EA910F32524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel ADD CONSTRAINT FK_90EA910F7A387E36 FOREIGN KEY (autore_barthel_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_barthel ADD CONSTRAINT FK_90EA910F32524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden DROP FOREIGN KEY FK_150FFD332524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden DROP FOREIGN KEY FK_150FFD348BA978');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden ADD CONSTRAINT FK_150FFD332524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_braden ADD CONSTRAINT FK_150FFD348BA978 FOREIGN KEY (autore_braden_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni DROP FOREIGN KEY FK_5286357732524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni DROP FOREIGN KEY FK_52863577AEB51382');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni ADD CONSTRAINT FK_5286357732524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_lesioni ADD CONSTRAINT FK_52863577AEB51382 FOREIGN KEY (autore_lesioni_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq DROP FOREIGN KEY FK_652E7A3F32524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq DROP FOREIGN KEY FK_652E7A3FD0161416');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq ADD CONSTRAINT FK_652E7A3F32524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_spmsq ADD CONSTRAINT FK_652E7A3FD0161416 FOREIGN KEY (autore_spmsq_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti DROP FOREIGN KEY FK_38D7D6432524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti DROP FOREIGN KEY FK_38D7D641FA7127F');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti ADD CONSTRAINT FK_38D7D6432524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_tinetti ADD CONSTRAINT FK_38D7D641FA7127F FOREIGN KEY (autore_tinetti_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas DROP FOREIGN KEY FK_D92348332524E3D');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas DROP FOREIGN KEY FK_D92348348FB292');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas ADD CONSTRAINT FK_D92348332524E3D FOREIGN KEY (scheda_pai_id) REFERENCES SCHEDA_PAI (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE SCHEDA_PAI_vas ADD CONSTRAINT FK_D92348348FB292 FOREIGN KEY (autore_vas_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
    }
}
